### ISSUE TITLE
App crash when using custom text files larger than screen

### ISSUE THREAD

**Issue by klebermagno** [Mithil467/mitype#7] opened 2020-04-05 19:20 UTC
### Subject of the issue
When I try use text larger that the screen the code broke.

### Your environment
* operating-system
Mac OS X Catalina
* version of Mitype
0.1.6
* version of Python
python 3.7.3
* which terminal and it's version if applicable
iterm

Problem may be in wrap_text method.

**Comment by Mithil467** [comment] 2020-04-05 19:36
Thanks for the issue @klebermagno
Can you please share the sample text file that you were trying to use? Also, it would be great if you could share the traceback output that you receive on the terminal upon terminal crash.

**Comment by Mithil467** [comment] 2020-04-05 23:26
I have made some changes now. 

It would be really great if you could test running from the source directly by following the steps given [here](https://github.com/Mithil467/mitype/blob/master/CONTRIBUTING.md) to see if the issue is indeed solved.
After confirmation, I can make a release with the latest changes.

Did the following changes - 

- Added message for user when screen size is insufficient to fit in all the lines of text (in https://github.com/Mithil467/mitype/commit/53fcfd08859404048382ac21bc178407276a3018). 
- I have taken care that if user passes a file with multiple whitespaces (like tabs, newlines), the text will have only a single space instead (in https://github.com/Mithil467/mitype/commit/b16e60f27fa91ee1c13c5aeab6c641a0feedfa39).

**Comment by Mithil467** [comment] 2020-04-11 21:42
I'm closing this issue. Feel free to open it if issue persists.

**Closed by Mithil467** 2020-04-11 21:42 UTC
Labels: bug, enhancement
